DROP TABLE IF EXISTS sms CASCADE;
DROP TABLE IF EXISTS mobile_provider CASCADE;
DROP TABLE IF EXISTS reminder CASCADE ;
DROP TABLE IF EXISTS pill_description CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- TODO: Add a column for tokens
-- User table
CREATE TABLE users(
    ID SERIAL PRIMARY KEY NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD_H TEXT NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    IS_ENGLISH BOOLEAN NOT NULL,
    TOKEN TEXT
);

-- Pill table
CREATE TABLE pill_description(
    ID SERIAL PRIMARY KEY NOT NULL,
    USER_ID INT REFERENCES users(ID),
    PILL_NAME TEXT NOT NULL,
    AMOUNT SMALLINT NOT NULL,
    STRENGTH TEXT,
    REMAINING SMALLINT
);

-- Reminder table
CREATE TABLE reminder(
    ID SERIAL PRIMARY KEY NOT NULL,
    PILL_ID INT NOT NULL REFERENCES pill_description(ID),
    DAY TEXT NOT NULL,
    DAY_TIME TIMESTAMPTZ NOT NULL
);

-- Mobile provider table
CREATE TABLE mobile_provider(
    ID SERIAL PRIMARY KEY NOT NULL,
    PROVIDER_URI VARCHAR(32) NOT NULL UNIQUE
);

-- SMS table
CREATE TABLE sms(
    ID SERIAL PRIMARY KEY NOT NULL,
    USERS_ID INT REFERENCES users(ID),
    PILL_DESCRIPTION_ID INT REFERENCES pill_description(ID),
    PHONE_PROVIDER SMALLINT REFERENCES mobile_provider(ID),
    PHONE_NUMBER SMALLINT NOT NULL
);

